# Generated by Django 5.2.8 on 2025-11-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diario",
            name="revistas",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
